services:
  - type: web
    name: geotree-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: DB_NAME
        value: users
      - key: JWT_SECRET
        sync: false
      - key: PHONEPE_MERCHANT_ID
        sync: false
      - key: PHONEPE_SALT_KEY
        sync: false
      - key: PHONEPE_SALT_INDEX
        value: 1
      - key: PHONEPE_BASE_URL
        value: https://api.phonepe.com/apis/hermes
      - key: APP_BASE_URL
        sync: false

